url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "HCI Lab" # the name of your site, e.g. ACME Corp.
description: "CNU Human-Computer Interaction Laboratory."
timezone: "Asia/Seoul"